services:

  caddy:
    image: caddy:latest
    container_name: caddy_sf8-vue3
    restart: unless-stopped
    ports:
      - "445:443"
    volumes:
      - ./docker/caddy/sf8-vue3.com+4.pem:/etc/cert/sf8-vue3/sf8-vue3.com+4.pem
      - ./docker/caddy/sf8-vue3.com+4-key.pem:/etc/cert/sf8-vue3/sf8-vue3.com+4-key.pem
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - .:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      php-fpm:
        condition: service_started

  node:
    image: node:20-alpine
    container_name: node_sf8-vue3
    working_dir: /srv
    volumes:
      - .:/srv
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run vite -- --host"

  # ---------------------------
  # PHP-FPM pour Symfony
  # ---------------------------
  php-fpm:
    build:
      context: ./docker/php
      args:
        TIMEZONE: Europe/Madrid
    container_name: php_sf8-vue3
    restart: unless-stopped
    ports:
      - "9001:9000"
    volumes:
      - .:/srv
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      database:
        condition: service_healthy

  # ---------------------------
  # PostgreSQL
  # ---------------------------
  database:
    container_name: postgres_sf8-vue3
    image: postgres:16-alpine
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: sf8-vue3
      POSTGRES_USER: sf8-vue3
      POSTGRES_DB: sf8-vue3
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sf8-vue3" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------
  # pgAdmin
  # ---------------------------
  pgadmin:
    container_name: pgadmin_sf8-vue3
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    depends_on:
      database:
        condition: service_healthy

volumes:
  caddy_data:
  caddy_config:

  ###> doctrine/doctrine-bundle ###
  database_data: ###< doctrine/doctrine-bundle ###
